### ISSUE TITLE
Execute only "selected" tests in Octane Pipeline

### ISSUE THREAD

**Issue by raka2407** [MicroFocus/octane-bamboo-plugin#35]
Hi, would it be possible to execute the octane pipeline with only the tests that are selected in Octane, instead of running the whole set of tests configured inside the bamboo plan. 

This might need some information (test case info) to be sent to Bamboo via Octane plugin and accordingly, bamboo plan is updated at run-time based on the arguments received from Octane via the pipeline.

**Comment by radislavB** [comment]
Generally , the question is Yes. 
See some details here : https://admhelp.microfocus.com/octane/en/CP10/Online/Content/AdminGuide/how-setup-testing-integration.htm

What is testing framework you use?

**Comment by raka2407** [comment]
Thanks for the quick response. We use robot framework.

**Comment by radislavB** [comment]
Do you know how to execute test selectively in robot framework?
can you send me example of such command?

**Comment by raka2407** [comment]
Robot Framework user guide below has information of various possibilities of executing test suites and test cases selectively. 

https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#selecting-test-cases

**Comment by radislavB** [comment]
Seems to me that option of "By test suite and test case names" can work.
Today we published beta version of plugin "v1.10.0.1-beta" that allows to do adjustments to most testing frameworks. Although its still in testing.

**Comment by raka2407** [comment]
Thanks, can you help me with the reference documentation to try this

**Comment by radislavB** [comment]
Most documentation is appear  in : https://admhelp.microfocus.com/octane/en/CP10/Online/Content/AdminGuide/how-setup-testing-integration.htm
In new beta version, we added option of "Custom" in Micro Focus ALM Octane testing framework converter task. That task contains some explanation/documentation about how to configure custom format.
If you want we can have a session, I will help you to configure. 
Do you have possibility to create Webex session?
Can you write me what is the company do you work for?

**Comment by radislavB** [comment]
https://microfocus.webex.com/join/ohad.samet
